# Generated by Django 2.2.11 on 2020-04-10 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20180811_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trackernotes', to='events.Feed')),
                ('sublist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackernotes', to='events.SubscriptionList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackernotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sublist', 'feed')},
            },
        ),
    ]
