#!/usr/bin/env bash

DJANGO_SETTINGS_MODULE=settings PYTHONPATH=. ./python_environment -u -W ignore /dev/stdin "$@" << EOF;
import django
django.setup()

import sys
sys.argv.pop(0) # /dev/stdin
fn = sys.argv[0]
with open(fn) as f:
    code = compile(f.read(), fn, 'exec')
    exec(code)
EOF
