#!/bin/sh
DJANGO_SETTINGS_MODULE=settings PYTHONPATH=. .env/bin/python -u -W ignore /dev/stdin "$@" << EOF;
import django
django.setup()

import sys
sys.argv.pop(0) # /dev/stdin
execfile(sys.argv[0])
EOF
