# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-02 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSupporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(max_length=96)),
                ('prefix', models.CharField(max_length=96)),
                ('firstname', models.CharField(max_length=96)),
                ('lastname', models.CharField(max_length=96)),
                ('address', models.CharField(max_length=96)),
                ('city', models.CharField(max_length=96)),
                ('state', models.CharField(max_length=96)),
                ('zipcode', models.CharField(max_length=96)),
                ('email', models.CharField(max_length=96)),
                ('message', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('geocode_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methods', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('collection_slug', models.CharField(max_length=128)),
                ('post_slug', models.CharField(max_length=128)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(db_index=True, max_length=64)),
                ('response_data', jsonfield.fields.JSONField()),
                ('executed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.CharField(max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=20)),
                ('anon_session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('reaction', jsonfield.fields.JSONField()),
                ('extra', jsonfield.fields.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sousveillance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=24)),
                ('req', jsonfield.fields.JSONField()),
                ('when', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massemail', models.BooleanField(default=True)),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('last_mass_email', models.IntegerField(default=0)),
                ('congressionaldistrict', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('paid_features', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('one_click_unsub_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('one_click_unsub_gendate', models.DateTimeField(blank=True, null=True)),
                ('one_click_unsub_hit', models.DateTimeField(blank=True, null=True)),
                ('research_anon_key', models.IntegerField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set([('subject', 'user'), ('subject', 'anon_session_key')]),
        ),
        migrations.AlterUniqueTogether(
            name='paypalpayment',
            unique_together=set([('user', 'created')]),
        ),
        migrations.AlterUniqueTogether(
            name='communityinterest',
            unique_together=set([('user', 'bill')]),
        ),
    ]
