# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20170906_0920'),
        ('website', '0002_auto_20170718_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.Bill'),
        ),
    ]
