# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_position_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
