# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_usergroupsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inactivity_warning_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
