# Generated by Django 2.2.28 on 2024-01-11 13:17

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210705_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(db_index=True, unique=True)),
                ('first_hit', models.DateTimeField(auto_now_add=True)),
                ('last_hit', models.DateTimeField(auto_now=True, db_index=True)),
                ('hits', models.IntegerField(db_index=True, default=1)),
                ('leadfeeder', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
            ],
        ),
    ]
