# Generated by Django 2.2.28 on 2024-01-12 16:11

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_ipaddrinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', markdownx.models.MarkdownxField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'index_together': {('published', 'created')},
            },
        ),

        migrations.AddField(
            model_name='userprofile',
            name='last_blog_post_emailed',
            field=models.IntegerField(default=0),
        ),
    ]
