# Generated by Django 2.2.28 on 2024-02-17 14:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='info',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
