# Generated by Django 2.2.28 on 2024-05-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20240425_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
