# Generated by Django 4.1.13 on 2025-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20240504_1651'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='website_blo_publish_a398ba_idx',
            old_fields=('published', 'created'),
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='website_blo_publish_8e4e65_idx',
            old_fields=('published', 'category', 'created'),
        ),
        migrations.RenameIndex(
            model_name='communitymessage',
            new_name='website_com_board_i_2f5b6e_idx',
            old_fields=('board', 'modified'),
        ),
    ]
