# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-02 07:29


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_type', models.IntegerField(blank=True, choices=[(1, b'Senate'), (2, b'Joint'), (3, b'House')], help_text=b'Whether this is a House, Senate, or Joint committee.', null=True)),
                ('code', models.CharField(db_index=True, help_text=b'An alphanumeric code used for the committee on THOMAS.gov, House.gov, and Senate.gov.', max_length=10, unique=True)),
                ('name', models.CharField(help_text=b"The name of the committee or subcommittee. Committee names typically look like '{House,Senate} Committee on ...', while subcommmittee names look like 'Legislative Branch'.", max_length=255)),
                ('url', models.CharField(blank=True, help_text=b"The committee's website.", max_length=255, null=True)),
                ('abbrev', models.CharField(blank=True, help_text=b'A really short abbreviation for the committee. Has no special significance.', max_length=255)),
                ('obsolete', models.BooleanField(db_index=True, default=False, help_text=b'True if this committee no longer exists.')),
                ('jurisdiction', models.TextField(blank=True, help_text=b"The committee's jurisdiction, if known.", null=True)),
                ('jurisdiction_link', models.TextField(blank=True, help_text=b'A link to where the jurisdiction text was sourced from.', null=True)),
                ('committee', models.ForeignKey(blank=True, help_text=b'This field indicates whether the object is a commmittee, in which case the committee field is null, or a subcommittee, in which case this field gives the parent committee.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcommittees', to='committee.Committee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('when', models.DateTimeField()),
                ('subject', models.TextField()),
                ('guid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('room', models.TextField(null=True)),
                ('bills', models.ManyToManyField(blank=True, to='bill.Bill')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='committee.Committee')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, b'Ex Officio'), (5, b'Member'), (3, b'Ranking Member'), (2, b'Chair'), (4, b'Vice Chair')], default=5, help_text=b'The role of the member on the committee.')),
                ('committee', models.ForeignKey(help_text=b'The committee or subcommittee being served on.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committee.Committee')),
                ('person', models.ForeignKey(help_text=b'The Member of Congress serving on a committee.', on_delete=django.db.models.deletion.CASCADE, related_name='committeeassignments', to='person.Person')),
            ],
        ),
    ]
