# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-02 07:29


from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.IntegerField(help_text=b'The number of the Congress in which the amendment was offered. The current Congress is 115.')),
                ('amendment_type', models.IntegerField(choices=[(3, b'S.Up.Amdt.'), (2, b'H.Amdt.'), (1, b'S.Amdt.')], help_text=b"The amendment's type, indicating the chmaber in which the amendment was offered.")),
                ('number', models.IntegerField(help_text=b"The amendment's number according to the Library of Congress's H.Amdt and S.Amdt numbering (just the integer part).")),
                ('sequence', models.IntegerField(blank=True, help_text=b'For House amendments, the sequence number of the amendment (unique within a bill).', null=True)),
                ('title', models.CharField(help_text=b'A title for the amendment.', max_length=255)),
                ('offered_date', models.DateField(help_text=b'The date the amendment was offered.')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b"The bill's primary display title, including its number.", max_length=255)),
                ('lock_title', models.BooleanField(default=False, help_text=b'Whether the title has been manually overridden.')),
                ('titles', jsonfield.fields.JSONField(default=None)),
                ('bill_type', models.IntegerField(choices=[(1, b'H.Res.'), (4, b'S.Res.'), (2, b'S.'), (7, b'H.J.Res.'), (8, b'S.J.Res.'), (3, b'H.R.'), (5, b'H.Con.Res.'), (6, b'S.Con.Res.')], help_text=b"The bill's type (e.g. H.R., S., H.J.Res. etc.)")),
                ('congress', models.IntegerField(help_text=b'The number of the Congress in which the bill was introduced. The current Congress is 115.')),
                ('number', models.IntegerField(help_text=b"The bill's number (just the integer part).")),
                ('current_status', models.IntegerField(choices=[(21, b'Vetoed & House Overrides (Senate Next)'), (16, b'Failed House'), (9, b'Passed House & Senate (President next)'), (28, 'Enacted \u2014 Signed by the President'), (26, b'Vetoed & Override Passed Senate, Failed in House'), (5, b'Passed Senate (House next)'), (8, b'Agreed To (Concurrent Resolution)'), (6, b'Agreed To (Simple Resolution)'), (24, b'Vetoed & Override Failed in House'), (29, 'Enacted \u2014 Veto Overridden'), (14, b'Failed to Resolve Differences'), (15, b'Vetoed (No Override Attempt)'), (22, b'Vetoed & Senate Overrides (House Next)'), (17, b'Failed Senate'), (19, b'Passed Senate, Failed House'), (12, b'Failed Under Suspension'), (10, b'Passed House with Changes (back to Senate)'), (31, b'Conference Report Agreed to by Senate (House next)'), (13, b'Failed Cloture'), (33, b'Enacted (Unknown Final Step)'), (4, b'Passed House (Senate next)'), (32, 'Enacted \u2014 By 10 Day Rule'), (27, b'Vetoed & Override Passed House, Failed in Senate'), (11, b'Passed Senate with Changes (back to House)'), (1, b'Introduced'), (30, b'Conference Report Agreed to by House (Senate next)'), (20, b'Passed House, Failed Senate'), (23, b'Pocket Vetoed'), (3, b'Ordered Reported'), (25, b'Vetoed & Override Failed in Senate'), (7, b'Agreed To (Constitutional Amendment Proposal)')], help_text=b'The current status of the bill.')),
                ('current_status_date', models.DateField(help_text=b'The date of the last major action on the bill corresponding to the current_status.')),
                ('introduced_date', models.DateField(help_text=b'The date the bill was introduced.')),
                ('major_actions', jsonfield.fields.JSONField(default=[])),
                ('committee_reports', jsonfield.fields.JSONField(blank=True, default=[], help_text=b'serialized list of committee report citations', null=True)),
                ('sliplawpubpriv', models.CharField(blank=True, choices=[(b'PUB', b'Public'), (b'PRI', b'Private')], help_text=b'For enacted laws, whether the law is a public (PUB) or private (PRI) law. Unique with congress and sliplawnum.', max_length=3, null=True)),
                ('sliplawnum', models.IntegerField(blank=True, help_text=b'For enacted laws, the slip law number (i.e. the law number in P.L. XXX-123). Unique with congress and sliplawpublpriv.', null=True)),
                ('source', models.CharField(choices=[(b'thomas-congproj', b'THOMAS.gov (via Congress Project)'), (b'statutesatlarge', b'U.S. Statutes at Large'), (b'americanmemory', b'LoC American Memory Collection')], help_text=b"The primary source for this bill's metadata.", max_length=16)),
                ('source_link', models.CharField(blank=True, help_text=b"When set, a link to the page on the primary source website for this bill. Set when source='americanmemory' only.", max_length=256, null=True)),
                ('docs_house_gov_postdate', models.DateTimeField(blank=True, help_text=b'The date on which the bill was posted to http://docs.house.gov (which is different from the date it was expected to be debated).', null=True)),
                ('senate_floor_schedule_postdate', models.DateTimeField(blank=True, help_text=b'The date on which the bill was posted on the Senate Floor Schedule (which is different from the date it was expected to be debated).', null=True)),
                ('scheduled_consideration_date', models.DateTimeField(blank=True, help_text=b'The date on which the bill is expected to be considered on the floor for the most recent of docs_house_gov_postdate and senate_floor_schedule_postdate, and if for docs.house.gov it is the week that this is the Monday of.', null=True)),
                ('text_incorporation', jsonfield.fields.JSONField(blank=True, default=[], help_text=b'What enacted bills have provisions of this bill been incorporated into?', null=True)),
            ],
            options={
                'ordering': ('congress', 'bill_type', 'number'),
            },
        ),
        migrations.CreateModel(
            name='BillLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='bill.Bill')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('source_text', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='oursummary', to='bill.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='BillTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_type', models.IntegerField(choices=[(1, b'Old'), (2, b'New')])),
                ('name', models.CharField(max_length=255)),
                ('subterms', models.ManyToManyField(blank=True, related_name='parents', to='bill.BillTerm')),
            ],
        ),
        migrations.CreateModel(
            name='BillTextComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver1', models.CharField(max_length=6)),
                ('ver2', models.CharField(max_length=6)),
                ('data', jsonfield.fields.JSONField()),
                ('bill1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons1', to='bill.Bill')),
                ('bill2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons2', to='bill.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Cosponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField(db_index=True, help_text=b"The date the cosponsor was added. It is always greater than or equal to the bill's introduced_date.")),
                ('withdrawn', models.DateField(blank=True, help_text=b'If the cosponsor withdrew his/her support, the date of withdrawl. Otherwise empty.', null=True)),
                ('bill', models.ForeignKey(help_text=b'The bill being cosponsored.', on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('person', models.ForeignKey(help_text=b'The cosponsoring person.', on_delete=django.db.models.deletion.PROTECT, to='person.Person')),
                ('role', models.ForeignKey(help_text=b'The role of the cosponsor at the time of cosponsorship.', on_delete=django.db.models.deletion.PROTECT, to='person.PersonRole')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=16)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedbills', to='bill.Bill')),
                ('related_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedtobills', to='bill.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='USCSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('level_type', models.CharField(choices=[(b'title', b'Title'), (b'subtitle', b'Subtitle'), (b'chapter', b'Chapter'), (b'subchapter', b'Subchapter'), (b'part', b'Part'), (b'subpart', b'Subpart'), (b'division', b'Division'), (b'heading', b'Heading'), (b'section', b'Section')], max_length=10)),
                ('number', models.CharField(blank=True, max_length=24, null=True)),
                ('deambig', models.IntegerField(default=0)),
                ('name', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField()),
                ('update_flag', models.IntegerField(default=0)),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.USCSection')),
            ],
        ),
    ]
