# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20170802_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='committees',
            field=models.ManyToManyField(blank=True, help_text=b'Committees to which the bill has been referred.', related_name='bills', to='committee.Committee'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='terms',
            field=models.ManyToManyField(blank=True, help_text=b'Subject areas associated with the bill.', related_name='bills', to='bill.BillTerm'),
        ),
    ]
