# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 10:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20171014_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='original_intent_replaced',
            field=models.NullBooleanField(help_text=b'Whether the bill has become the vehicle for passage of an unrelated measure *and* the original substance of the bill is completely gone. Set to False to flag that the enacted bill has been reviewed and it was not a vehicle.'),
        ),
    ]
