# Generated by Django 2.0.8 on 2018-08-11 13:42

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20180106_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='amendment_type',
            field=models.IntegerField(choices=[(2, 'H.Amdt.'), (3, 'S.Up.Amdt.'), (1, 'S.Amdt.')], help_text="The amendment's type, indicating the chmaber in which the amendment was offered."),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='bill',
            field=models.ForeignKey(help_text='The bill the amendment amends.', on_delete=django.db.models.deletion.PROTECT, to='bill.Bill'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='congress',
            field=models.IntegerField(help_text='The number of the Congress in which the amendment was offered. The current Congress is 115.'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='number',
            field=models.IntegerField(help_text="The amendment's number according to the Library of Congress's H.Amdt and S.Amdt numbering (just the integer part)."),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='offered_date',
            field=models.DateField(help_text='The date the amendment was offered.'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='sequence',
            field=models.IntegerField(blank=True, help_text='For House amendments, the sequence number of the amendment (unique within a bill).', null=True),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='The sponsor of the amendment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_amendments', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='sponsor_role',
            field=models.ForeignKey(blank=True, help_text='The role of the sponsor of the amendment at the time the amendment was offered.', null=True, on_delete=django.db.models.deletion.PROTECT, to='person.PersonRole'),
        ),
        migrations.AlterField(
            model_name='amendment',
            name='title',
            field=models.CharField(help_text='A title for the amendment.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.IntegerField(choices=[(7, 'H.J.Res.'), (4, 'S.Res.'), (6, 'S.Con.Res.'), (1, 'H.Res.'), (5, 'H.Con.Res.'), (3, 'H.R.'), (8, 'S.J.Res.'), (2, 'S.')], help_text="The bill's type (e.g. H.R., S., H.J.Res. etc.)"),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committee_reports',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text='serialized list of committee report citations', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committees',
            field=models.ManyToManyField(blank=True, help_text='Committees to which the bill has been referred.', related_name='bills', to='committee.Committee'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='congress',
            field=models.IntegerField(help_text='The number of the Congress in which the bill was introduced. The current Congress is 115.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cosponsors',
            field=models.ManyToManyField(blank=True, help_text="The bill's cosponsors.", through='bill.Cosponsor', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='current_status',
            field=models.IntegerField(choices=[(24, 'Vetoed & Override Failed in House'), (1, 'Introduced'), (11, 'Passed Senate with Changes (back to House)'), (27, 'Vetoed & Override Passed House, Failed in Senate'), (12, 'Failed Under Suspension'), (30, 'Conference Report Agreed to by House (Senate next)'), (23, 'Pocket Vetoed'), (22, 'Vetoed & Senate Overrides (House Next)'), (33, 'Enacted (Unknown Final Step)'), (3, 'Ordered Reported'), (8, 'Agreed To (Concurrent Resolution)'), (4, 'Passed House (Senate next)'), (26, 'Vetoed & Override Passed Senate, Failed in House'), (5, 'Passed Senate (House next)'), (31, 'Conference Report Agreed to by Senate (House next)'), (28, 'Enacted — Signed by the President'), (6, 'Agreed To (Simple Resolution)'), (16, 'Failed House'), (32, 'Enacted — By 10 Day Rule'), (20, 'Passed House, Failed Senate'), (14, 'Failed to Resolve Differences'), (9, 'Passed House & Senate (President next)'), (25, 'Vetoed & Override Failed in Senate'), (15, 'Vetoed (No Override Attempt)'), (21, 'Vetoed & House Overrides (Senate Next)'), (10, 'Passed House with Changes (back to Senate)'), (29, 'Enacted — Veto Overridden'), (17, 'Failed Senate'), (7, 'Agreed To (Constitutional Amendment Proposal)'), (19, 'Passed Senate, Failed House'), (13, 'Failed Cloture')], help_text='The current status of the bill.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='current_status_date',
            field=models.DateField(help_text='The date of the last major action on the bill corresponding to the current_status.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='docs_house_gov_postdate',
            field=models.DateTimeField(blank=True, help_text='The date on which the bill was posted to http://docs.house.gov (which is different from the date it was expected to be debated).', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='introduced_date',
            field=models.DateField(help_text='The date the bill was introduced.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='lock_title',
            field=models.BooleanField(default=False, help_text='Whether the title has been manually overridden.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.IntegerField(help_text="The bill's number (just the integer part)."),
        ),
        migrations.AlterField(
            model_name='bill',
            name='original_intent_replaced',
            field=models.NullBooleanField(help_text='Whether the bill has become the vehicle for passage of an unrelated measure *and* the original substance of the bill is completely gone. Set to False to flag that the enacted bill has been reviewed and it was not a vehicle.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='scheduled_consideration_date',
            field=models.DateTimeField(blank=True, help_text='The date on which the bill is expected to be considered on the floor for the most recent of docs_house_gov_postdate and senate_floor_schedule_postdate, and if for docs.house.gov it is the week that this is the Monday of.', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='senate_floor_schedule_postdate',
            field=models.DateTimeField(blank=True, help_text='The date on which the bill was posted on the Senate Floor Schedule (which is different from the date it was expected to be debated).', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sliplawnum',
            field=models.IntegerField(blank=True, help_text='For enacted laws, the slip law number (i.e. the law number in P.L. XXX-123). Unique with congress and sliplawpublpriv.', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sliplawpubpriv',
            field=models.CharField(blank=True, choices=[('PUB', 'Public'), ('PRI', 'Private')], help_text='For enacted laws, whether the law is a public (PUB) or private (PRI) law. Unique with congress and sliplawnum.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='source',
            field=models.CharField(choices=[('thomas-congproj', 'THOMAS.gov (via Congress Project)'), ('statutesatlarge', 'U.S. Statutes at Large'), ('americanmemory', 'LoC American Memory Collection')], help_text="The primary source for this bill's metadata.", max_length=16),
        ),
        migrations.AlterField(
            model_name='bill',
            name='source_link',
            field=models.CharField(blank=True, help_text="When set, a link to the page on the primary source website for this bill. Set when source='americanmemory' only.", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='The primary sponsor of the bill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_bills', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor_role',
            field=models.ForeignKey(blank=True, help_text='The role of the primary sponsor of the bill at the time the bill was introduced.', null=True, on_delete=django.db.models.deletion.PROTECT, to='person.PersonRole'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='terms',
            field=models.ManyToManyField(blank=True, help_text='Subject areas associated with the bill.', related_name='bills', to='bill.BillTerm'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='text_incorporation',
            field=jsonfield.fields.JSONField(blank=True, default=[], help_text='What enacted bills have provisions of this bill been incorporated into?', null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(help_text="The bill's primary display title, including its number.", max_length=255),
        ),
        migrations.AlterField(
            model_name='billterm',
            name='term_type',
            field=models.IntegerField(choices=[(2, 'New'), (1, 'Old')]),
        ),
        migrations.AlterField(
            model_name='cosponsor',
            name='bill',
            field=models.ForeignKey(help_text='The bill being cosponsored.', on_delete=django.db.models.deletion.CASCADE, to='bill.Bill'),
        ),
        migrations.AlterField(
            model_name='cosponsor',
            name='joined',
            field=models.DateField(db_index=True, help_text="The date the cosponsor was added. It is always greater than or equal to the bill's introduced_date."),
        ),
        migrations.AlterField(
            model_name='cosponsor',
            name='person',
            field=models.ForeignKey(help_text='The cosponsoring person.', on_delete=django.db.models.deletion.PROTECT, to='person.Person'),
        ),
        migrations.AlterField(
            model_name='cosponsor',
            name='role',
            field=models.ForeignKey(help_text='The role of the cosponsor at the time of cosponsorship.', on_delete=django.db.models.deletion.PROTECT, to='person.PersonRole'),
        ),
        migrations.AlterField(
            model_name='cosponsor',
            name='withdrawn',
            field=models.DateField(blank=True, help_text='If the cosponsor withdrew his/her support, the date of withdrawl. Otherwise empty.', null=True),
        ),
        migrations.AlterField(
            model_name='uscsection',
            name='level_type',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('chapter', 'Chapter'), ('subchapter', 'Subchapter'), ('part', 'Part'), ('subpart', 'Subpart'), ('division', 'Division'), ('heading', 'Heading'), ('section', 'Section')], max_length=10),
        ),
    ]
