# Generated by Django 2.1.7 on 2020-03-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20180811_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtextcomparison',
            name='ver1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billtextcomparison',
            name='ver2',
            field=models.CharField(max_length=10),
        ),
    ]
