# Generated by Django 2.0.8 on 2018-08-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='category',
            field=models.IntegerField(choices=[(5, 'Passage (Part)'), (3, 'Passage'), (4, 'Cloture'), (6, 'Nomination'), (13, 'Impeachment'), (10, 'Veto Override'), (11, 'Conviction'), (12, 'Treaty Ratification'), (9, 'Unknown Category'), (7, 'Procedural'), (1, 'Amendment'), (2, 'Passage under Suspension')], help_text='The type of the vote.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='chamber',
            field=models.IntegerField(choices=[(1, 'Senate'), (2, 'House')], help_text='The chamber in which the vote was held, House or Senate.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='congress',
            field=models.IntegerField(help_text='The number of the Congress in which the vote took place. The current Congress is 115. In recent history Congresses are two years; however, this was not always the case.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(db_index=True, help_text='The date (and in recent history also time) on which the vote was held.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='margin',
            field=models.FloatField(blank=True, help_text="The absolute value of the difference in the percent of positive votes and negative votes. Null for votes that aren't yes/no (like election of the speaker, quorum calls).", null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='missing_data',
            field=models.BooleanField(default=False, help_text='If something in the source could be parsed and we should revisit the file.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='number',
            field=models.IntegerField(help_text='The number of the vote, unique to a Congress, session, and chamber.', verbose_name='Vote Number'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='percent_plus',
            field=models.FloatField(blank=True, help_text="The percent of positive votes. Null for votes that aren't yes/no (like election of the speaker, quorum calls).", null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.TextField(help_text='Descriptive text for what the vote was about.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='question_details',
            field=models.TextField(blank=True, help_text='Additional descriptive text for what the vote was about.', null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='related_amendment',
            field=models.ForeignKey(blank=True, help_text='A related amendment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='bill.Amendment'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='related_bill',
            field=models.ForeignKey(blank=True, help_text='A related bill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='bill.Bill'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='required',
            field=models.CharField(help_text="A code indicating what number of votes was required for success. Often '1/2' or '3/5'. This field should be interpreted with care. It comes directly from the upstream source and may need some 'unpacking.' For instance, while 1/2 always mean 1/2 of those voting (i.e. excluding absent and abstain), 3/5 in some cases means to include absent/abstain and in other cases to exclude.", max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='result',
            field=models.TextField(help_text='Descriptive text for the result of the vote.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='session',
            field=models.CharField(help_text='Within each Congress there are sessions. In recent history the sessions correspond to calendar years and are named accordingly. However, in historical data the sessions may be named in completely other ways, such as with letters A, B, and C. Session names are unique *within* a Congress.', max_length=4),
        ),
        migrations.AlterField(
            model_name='vote',
            name='source',
            field=models.IntegerField(choices=[(1, 'senate.gov'), (2, 'house.gov'), (3, 'VoteView.com')], help_text='The source of the vote information.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='total_minus',
            field=models.IntegerField(blank=True, default=0, help_text='The count of negative votes (nay/no).'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='total_other',
            field=models.IntegerField(blank=True, default=0, help_text='The count of abstain or absent voters.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='total_plus',
            field=models.IntegerField(blank=True, default=0, help_text='The count of positive votes (aye/yea).'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(help_text='Descriptive text for the type of the vote.', max_length=255),
        ),
        migrations.AlterField(
            model_name='voter',
            name='created',
            field=models.DateTimeField(db_index=True, help_text='The date (and in recent history also time) on which the vote was held.'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='option',
            field=models.ForeignKey(help_text='How the person voted.', on_delete=django.db.models.deletion.CASCADE, to='vote.VoteOption'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='person',
            field=models.ForeignKey(blank=True, help_text='The person who cast this vote. May be null if the information could not be determined.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='person_role',
            field=models.ForeignKey(blank=True, help_text='The role of the person who cast this vote at the time of the vote. May be null if the information could not be determined.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='person.PersonRole'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote',
            field=models.ForeignKey(help_text='The vote that this record is a part of.', on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='vote.Vote'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (3, 'Member of Congress'), (2, 'Vice President')], help_text='Whether the voter was a Member of Congress or the Vice President.'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voteview_extra_code',
            field=models.CharField(help_text='Extra information provided in the voteview data.', max_length=20),
        ),
    ]
