# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-02 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=100)),
                ('checksum', models.CharField(max_length=8)),
                ('processed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
