# Generated by Django 2.0.8 on 2018-08-11 13:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bioguideid',
            field=models.CharField(blank=True, help_text="The person's ID on bioguide.congress.gov. May be null if the person served only as a president and not in Congress.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, help_text="The person's birthday.", null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cspanid',
            field=models.IntegerField(blank=True, help_text='The ID of the person on CSPAN websites, if known.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(help_text="The person's first name or first initial.", max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], help_text="The person's gender, if known. For historical data, the gender is sometimes not known.", null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(help_text="The person's last name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='middlename',
            field=models.CharField(blank=True, help_text="The person's middle name (optional).", max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text="The person's full name with title, district, and party information for current Members of Congress, in a typical display format.", max_length=96),
        ),
        migrations.AlterField(
            model_name='person',
            name='namemod',
            field=models.CharField(blank=True, help_text="The suffix on the person's name usually one of Jr., Sr., I, II, etc.", max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, help_text='The person\'s nickname. If set, the nickname should usually be displayed in quotes where a middle name would go. For instance, Joe "Buster" Smith.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='osid',
            field=models.CharField(blank=True, help_text="The person's ID on opensecrets.org (The Center for Responsive Politics), if known.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pvsid',
            field=models.CharField(blank=True, help_text="The person's ID on vote-smart.org (Project Vote Smart), if known.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sortname',
            field=models.CharField(help_text="The person's name suitable for sorting lexicographically by last name or for display in a sorted list of names. Title, district, and party information are included for current Members of Congress.", max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitterid',
            field=models.CharField(blank=True, help_text="The name of the person's official Twitter handle, if known.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='youtubeid',
            field=models.CharField(blank=True, help_text="The name of the person's official YouTube channel, if known.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='caucus',
            field=models.CharField(blank=True, help_text='For independents, the party that the legislator caucuses with. If changed during a term, the most recent.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='current',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], db_index=True, default=False, help_text='Whether the role is currently held, or if this is archival information.'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='district',
            field=models.IntegerField(blank=True, db_index=True, help_text='For representatives, the number of their congressional district. 0 for at-large districts, -1 in historical data if the district is not known.', null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='enddate',
            field=models.DateField(db_index=True, help_text='The date the role ended (when the person resigned, died, etc.)'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, help_text='Additional schema-less information stored with this object.', null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='leadership_title',
            field=models.CharField(blank=True, help_text='The last known leadership role held during this role, if any.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='party',
            field=models.CharField(blank=True, db_index=True, help_text='The political party of the person. If the person changes party, it is usually the most recent party during this role.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='phone',
            field=models.CharField(blank=True, help_text='The last known phone number of the DC congressional office during this role, if known.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='role_type',
            field=models.IntegerField(choices=[(2, 'Representative'), (1, 'Senator'), (3, 'President'), (4, 'Vice President')], db_index=True, help_text='The type of this role: a U.S. senator, a U.S. congressperson, a U.S. president, or a U.S. vice president.'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='senator_class',
            field=models.IntegerField(blank=True, choices=[(2, 'Class 2'), (1, 'Class 1'), (3, 'Class 3')], db_index=True, help_text='For senators, their election class, which determines which years they are up for election. (It has nothing to do with seniority.)', null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='senator_rank',
            field=models.IntegerField(blank=True, choices=[(2, 'Junior'), (1, 'Senior')], help_text='For senators, their state rank, i.e. junior or senior. For historical data, this is their last known rank.', null=True),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='startdate',
            field=models.DateField(db_index=True, help_text='The date the role began (when the person took office).'),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='state',
            field=models.CharField(blank=True, choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('DK', 'Dakota Territory'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OL', 'Territory of Orleans'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PI', 'Philippines'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], db_index=True, help_text='For senators and representatives, the two-letter USPS abbrevation for the state or territory they are serving. Values are the abbreviations for the 50 states (each of which have at least one representative and two senators, assuming no vacancies) plus DC, PR, and the island territories AS, GU, MP, and VI (all of which have a non-voting delegate), and for really old historical data you will also find PI (Philippines, 1907-1946), DK (Dakota Territory, 1861-1889), and OR (Orleans Territory, 1806-1811) for non-voting delegates.', max_length=2),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='website',
            field=models.CharField(blank=True, help_text='The URL to the official website of the person during this role, if known.', max_length=255),
        ),
    ]
