# Generated by Django 2.2.24 on 2022-12-22 06:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [('person', '0003_auto_20221222_0618'), ('person', '0004_auto_20221222_0637')]

    dependencies = [
        ('person', '0002_auto_20180811_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fediverse_webfinger',
            field=jsonfield.fields.JSONField(blank=True, help_text="The person's official (not campaign) Mastodon account's webfinger record, or a stub.", null=True),
        ),
    ]
