# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.NullBooleanField(default=None, help_text='Whether this organization has been verified (True), if verification was denied (False), or if verification is pending (None).')),
                ('name', models.CharField(help_text='The display name of the stakeholder.', max_length=150)),
                ('slug', models.SlugField(help_text='The slug used in URLs.')),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, default={}, help_text='Additional information stored with this object.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('admins', models.ManyToManyField(help_text='The users who can manage information about this stakeholder.', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
