# This file (except this top part) was generated from the Sunlight
# Labs Open States API, using the following code.
#
# from us import statenames
# from settings import SUNLIGHTLABS_API_KEY
# from urllib import urlopen
# import json, pprint
#
# states_metadata = { }
# for state in statenames:
#  try:
#   states_metadata[state] = json.load(urlopen("http://openstates.org/api/v1/metadata/%s?apikey=%s" % (state.lower(), SUNLIGHTLABS_API_KEY)))
#  except ValueError:
#   print state
# pprint.pprint(states_metadata, open("states/openstates_metadata.py", "w")) # warning: overwrites this comment

stata_metadata = \
{'AK': {u'abbreviation': u'ak',
        u'feature_flags': [u'subjects'],
        u'id': u'ak',
        u'latest_csv_date': u'2012-05-01 09:01:22',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ak-csv.zip',
        u'latest_json_date': u'2012-05-01 15:43:47',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ak-json.zip',
        u'latest_update': u'2012-05-27 00:51:57',
        u'legislature_name': u'The Alaska State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Alaska',
        u'session_details': {u'26': {u'display_name': u'26th Legislature'},
                             u'27': {u'display_name': u'27th Legislature'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'26',
                    u'sessions': [u'26'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'27',
                    u'sessions': [u'27'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'AL': {u'abbreviation': u'al',
        u'feature_flags': [u'subjects'],
        u'id': u'al',
        u'latest_csv_date': u'2012-05-01 09:12:41',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-al-csv.zip',
        u'latest_json_date': u'2012-05-02 00:36:17',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-al-json.zip',
        u'latest_update': u'2012-05-27 00:08:07',
        u'legislature_name': u'Alabama Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 4,
        u'lower_chamber_title': u'Representative',
        u'name': u'Alabama',
        u'session_details': {u'2011rs': {u'display_name': u'2011 Regular Session',
                                         u'internal_id': u'1058',
                                         u'type': u'primary'},
                             u'2012rs': {u'display_name': u'2012 Regular Session',
                                         u'internal_id': u'1059',
                                         u'type': u'primary'},
                             u'First Special Session 2012': {u'display_name': u'First Special Session 2012',
                                                             u'internal_id': u'1060',
                                                             u'type': u'special'}},
        u'terms': [{u'end_year': 2014,
                    u'name': u'2011-2014',
                    u'sessions': [u'2011rs',
                                  u'2012rs',
                                  u'First Special Session 2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'AR': {u'abbreviation': u'ar',
        u'feature_flags': [],
        u'id': u'ar',
        u'latest_csv_date': u'2012-05-01 09:01:32',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ar-csv.zip',
        u'latest_json_date': u'2012-05-01 15:48:41',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ar-json.zip',
        u'latest_update': u'2012-05-27 02:52:57',
        u'legislature_name': u'Arkansas General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Arkansas',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session',
                                       u'end_date': u'2011-04-27 00:00:00',
                                       u'slug': u'2011R',
                                       u'start_date': u'2011-01-10 00:00:00',
                                       u'type': u'primary'},
                             u'2012F': {u'display_name': u'2012 Fiscal Session',
                                        u'slug': u'2012F',
                                        u'start_date': u'2012-02-13 00:00:00',
                                        u'type': u'special'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012F'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'AZ': {u'abbreviation': u'az',
        u'feature_flags': [u'events'],
        u'id': u'az',
        u'latest_csv_date': u'2012-05-01 09:01:49',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-az-csv.zip',
        u'latest_json_date': u'2012-05-01 15:58:51',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-az-json.zip',
        u'latest_update': u'2012-05-27 03:25:33',
        u'legislature_name': u'Arizona State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Arizona',
        u'session_details': {u'49th-1st-regular': {u'display_name': u'49th Legislature, 1st Regular Session',
                                                   u'end_date': u'2009-07-01 00:00:00',
                                                   u'session_id': 87,
                                                   u'start_date': u'2009-01-12 00:00:00',
                                                   u'type': u'primary'},
                             u'49th-1st-special': {u'display_name': u'49th Legislature, 1st Special Session',
                                                   u'end_date': u'2009-01-31 00:00:00',
                                                   u'session_id': 89,
                                                   u'start_date': u'2009-01-28 00:00:00',
                                                   u'type': u'special'},
                             u'49th-2nd-regular': {u'display_name': u'49th Legislature, 2nd Regular Session',
                                                   u'end_date': u'2010-04-29 00:00:00',
                                                   u'session_id': 93,
                                                   u'start_date': u'2010-01-11 00:00:00',
                                                   u'type': u'primary'},
                             u'49th-2nd-special': {u'display_name': u'49th Legislature, 2nd Special Session',
                                                   u'end_date': u'2009-05-27 00:00:00',
                                                   u'session_id': 90,
                                                   u'start_date': u'2009-05-21 00:00:00',
                                                   u'type': u'special'},
                             u'49th-3rd-special': {u'display_name': u'49th Legislature, 3rd Special Session',
                                                   u'end_date': u'2009-08-25 00:00:00',
                                                   u'session_id': 91,
                                                   u'start_date': u'2009-07-06 00:00:00',
                                                   u'type': u'special'},
                             u'49th-4th-special': {u'display_name': u'49th Legislature, 4th Special Session',
                                                   u'end_date': u'2009-11-23 00:00:00',
                                                   u'session_id': 92,
                                                   u'start_date': u'2009-11-17 00:00:00',
                                                   u'type': u'special'},
                             u'49th-5th-special': {u'display_name': u'49th Legislature, 5th Special Session',
                                                   u'end_date': u'2009-12-19 00:00:00',
                                                   u'session_id': 94,
                                                   u'start_date': u'2009-12-17 00:00:00',
                                                   u'type': u'special'},
                             u'49th-6th-special': {u'display_name': u'49th Legislature, 6th Special Session',
                                                   u'end_date': u'2010-02-11 00:00:00',
                                                   u'session_id': 95,
                                                   u'start_date': u'2010-02-01 00:00:00',
                                                   u'type': u'special'},
                             u'49th-7th-special': {u'display_name': u'49th Legislature, 7th Special Session',
                                                   u'end_date': u'2010-03-16 00:00:00',
                                                   u'session_id': 96,
                                                   u'start_date': u'2010-03-08 00:00:00',
                                                   u'type': u'special'},
                             u'49th-8th-special': {u'display_name': u'49th Legislature, 8th Special Session',
                                                   u'end_date': u'2010-04-01 00:00:00',
                                                   u'session_id': 101,
                                                   u'start_date': u'2010-03-29 00:00:00',
                                                   u'type': u'special'},
                             u'49th-9th-special': {u'display_name': u'49th Legislature, 9th Special Session',
                                                   u'end_date': u'2010-08-11 00:00:00',
                                                   u'session_id': 103,
                                                   u'start_date': u'2010-08-09 00:00:00',
                                                   u'type': u'special'},
                             u'50th-1st-regular': {u'display_name': u'50th Legislature, 1st Regular Session',
                                                   u'end_date': u'2011-04-20 00:00:00',
                                                   u'session_id': 102,
                                                   u'start_date': u'2011-01-10 00:00:00',
                                                   u'type': u'primary'},
                             u'50th-1st-special': {u'display_name': u'50th Legislature, 1st Special Session',
                                                   u'end_date': u'2011-01-20 00:00:00',
                                                   u'session_id': 104,
                                                   u'start_date': u'2011-01-19 00:00:00',
                                                   u'type': u'special'},
                             u'50th-2nd-regular': {u'display_name': u'50th Legislature, 2nd Regular Session',
                                                   u'session_id': 107,
                                                   u'type': u'primary'},
                             u'50th-2nd-special': {u'display_name': u'50th Legislature, 2nd Special Session',
                                                   u'end_date': u'2011-02-16 00:00:00',
                                                   u'session_id': 105,
                                                   u'start_date': u'2011-02-14 00:00:00',
                                                   u'type': u'special'},
                             u'50th-3rd-special': {u'display_name': u'50th Legislature, 3rd Special Session',
                                                   u'end_date': u'2011-06-13 00:00:00',
                                                   u'session_id': 106,
                                                   u'start_date': u'2011-06-10 00:00:00',
                                                   u'type': u'special'},
                             u'50th-4th-special': {u'display_name': u'50th Legislature, 4th Special Session',
                                                   u'end_date': u'2011-11-01 00:00:00',
                                                   u'session_id': 108,
                                                   u'start_date': u'2011-11-01 00:00:00',
                                                   u'type': u'special'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'49',
                    u'sessions': [u'49th-1st-special',
                                  u'49th-2nd-special',
                                  u'49th-1st-regular',
                                  u'49th-3rd-special',
                                  u'49th-4th-special',
                                  u'49th-5th-special',
                                  u'49th-6th-special',
                                  u'49th-7th-special',
                                  u'49th-8th-special',
                                  u'49th-2nd-regular',
                                  u'49th-9th-special'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'50',
                    u'sessions': [u'50th-1st-special',
                                  u'50th-2nd-special',
                                  u'50th-3rd-special',
                                  u'50th-4th-special',
                                  u'50th-1st-regular',
                                  u'50th-2nd-regular'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'CA': {u'abbreviation': u'ca',
        u'feature_flags': [u'subjects'],
        u'id': u'ca',
        u'latest_csv_date': u'2012-05-01 09:11:24',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ca-csv.zip',
        u'latest_json_date': u'2012-05-02 14:48:22',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-ca-json.zip',
        u'latest_update': u'2012-05-26 00:19:04',
        u'legislature_name': u'California State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'Assembly',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Assemblymember',
        u'name': u'California',
        u'session_details': {u'20092010': {u'display_name': u'2009-2010 Regular Session',
                                           u'start_date': u'2008-12-01 00:00:00',
                                           u'type': u'primary'},
                             u'20092010 Special Session 1': {u'display_name': u'2009-2010, 1st Special Session',
                                                             u'type': u'special'},
                             u'20092010 Special Session 2': {u'display_name': u'2009-2010, 2nd Special Session',
                                                             u'type': u'special'},
                             u'20092010 Special Session 3': {u'display_name': u'2009-2010, 3rd Special Session',
                                                             u'type': u'special'},
                             u'20092010 Special Session 4': {u'display_name': u'2009-2010, 4th Special Session',
                                                             u'type': u'special'},
                             u'20092010 Special Session 5': {u'display_name': u'2009-2010, 5th Special Session',
                                                             u'type': u'special'},
                             u'20092010 Special Session 6': {u'display_name': u'2009-2010, 6th Special Session',
                                                             u'type': u'special'},
                             u'20092010 Special Session 7': {u'display_name': u'2009-2010, 7th Special Session',
                                                             u'type': u'special'},
                             u'20092010 Special Session 8': {u'display_name': u'2009-2010, 8th Special Session',
                                                             u'type': u'special'},
                             u'20112012': {u'display_name': u'2011-2012 Regular Session',
                                           u'start_date': u'2010-12-06 00:00:00',
                                           u'type': u'primary'},
                             u'20112012 Special Session 1': {u'display_name': u'2011-2012, 1st Special Session',
                                                             u'type': u'special'}},
        u'terms': [{u'+start_date': u'2008-12-01 00:00:00',
                    u'end_year': 2010,
                    u'name': u'20092010',
                    u'sessions': [u'20092010',
                                  u'20092010 Special Session 1',
                                  u'20092010 Special Session 2',
                                  u'20092010 Special Session 3',
                                  u'20092010 Special Session 4',
                                  u'20092010 Special Session 5',
                                  u'20092010 Special Session 6',
                                  u'20092010 Special Session 7',
                                  u'20092010 Special Session 8'],
                    u'start_year': 2009},
                   {u'+start_date': u'2010-12-06 00:00:00',
                    u'end_year': 2012,
                    u'name': u'20112012',
                    u'sessions': [u'20112012 Special Session 1',
                                  u'20112012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'CO': {u'abbreviation': u'co',
        u'feature_flags': [],
        u'id': u'co',
        u'latest_csv_date': u'2012-05-01 09:12:44',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-co-csv.zip',
        u'latest_json_date': u'2012-05-02 00:38:51',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-co-json.zip',
        u'latest_update': u'2012-05-27 00:59:51',
        u'legislature_name': u'Colorado General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Colorado',
        u'session_details': {u'2011A': {u'display_name': u'2011 Regular Session',
                                        u'start_date': u'2011-01-26 00:00:00',
                                        u'type': u'primary'},
                             u'2012A': {u'display_name': u'2012 Regular Session',
                                        u'start_date': u'2012-01-11 00:00:00',
                                        u'type': u'primary'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011A', u'2012A'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'CT': {u'abbreviation': u'ct',
        u'feature_flags': [u'subjects'],
        u'id': u'ct',
        u'latest_csv_date': u'2012-05-01 09:08:16',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ct-csv.zip',
        u'latest_json_date': u'2012-05-01 22:15:53',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ct-json.zip',
        u'latest_update': u'2012-05-27 03:29:32',
        u'legislature_name': u'Connecticut General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Connecticut',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session'},
                             u'2012': {u'display_name': u'2012 Regular Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'DC': {u'abbreviation': u'dc',
        u'feature_flags': [],
        u'id': u'dc',
        u'latest_csv_date': u'2012-05-01 09:00:55',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-dc-csv.zip',
        u'latest_json_date': u'2012-05-01 15:24:02',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-dc-json.zip',
        u'latest_update': u'2012-05-27 02:36:59',
        u'legislature_name': u'Council of the District of Columbia',
        u'level': u'state',
        u'name': u'District of Columbia',
        u'session_details': {u'19': {u'display_name': u'19th Council Period'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'19'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Council',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Councilmember'},
 'DE': {u'abbreviation': u'de',
        u'feature_flags': [u'events'],
        u'id': u'de',
        u'latest_csv_date': u'2012-05-01 09:12:45',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-de-csv.zip',
        u'latest_json_date': u'2012-05-02 00:40:10',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-de-json.zip',
        u'latest_update': u'2012-05-27 01:48:26',
        u'legislature_name': u'Delaware General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Delaware',
        u'session_details': {u'146': {u'display_name': u'146th General Assembly'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'146'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'FL': {u'abbreviation': u'fl',
        u'feature_flags': [],
        u'id': u'fl',
        u'latest_csv_date': u'2012-05-01 09:01:55',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-fl-csv.zip',
        u'latest_json_date': u'2012-05-01 16:06:37',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-fl-json.zip',
        u'latest_update': u'2012-05-27 01:16:30',
        u'legislature_name': u'Florida Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Florida',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session'},
                             u'2012': {u'display_name': u'2012 Regular Session'},
                             u'2012B': {u'display_name': u'2012 Extraordinary Apportionment Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012', u'2012B'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'GA': {u'abbreviation': u'ga',
        u'feature_flags': [],
        u'id': u'ga',
        u'latest_csv_date': u'2012-05-01 09:12:07',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ga-csv.zip',
        u'latest_json_date': u'2012-05-02 00:15:24',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-ga-json.zip',
        u'latest_update': u'2012-05-27 00:07:04',
        u'legislature_name': u'Georgia General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Georgia',
        u'session_details': {u'2011_12': {u'display_name': u'2011-2012 Regular Session'},
                             u'2011_ss': {u'display_name': u'2011 Special Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011_12', u'2011_ss'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'HI': {u'abbreviation': u'hi',
        u'feature_flags': [u'subjects'],
        u'id': u'hi',
        u'latest_csv_date': u'2012-05-01 09:08:30',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-hi-csv.zip',
        u'latest_json_date': u'2012-05-01 22:26:53',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-hi-json.zip',
        u'latest_update': u'2012-05-27 02:20:59',
        u'legislature_name': u'Hawaii State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Hawaii',
        u'session_details': {u'2011 Regular Session': {u'display_name': u'2011-2012 Regular Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011 Regular Session'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'IA': {u'abbreviation': u'ia',
        u'feature_flags': [],
        u'id': u'ia',
        u'latest_csv_date': u'2012-05-01 09:11:57',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ia-csv.zip',
        u'latest_json_date': u'2012-05-02 00:02:54',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-ia-json.zip',
        u'latest_update': u'2012-05-27 01:56:24',
        u'legislature_name': u'Iowa General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Iowa',
        u'session_details': {u'2011-2012': {u'display_name': u'2011-2012 Regular Session',
                                            u'end_date': u'2013-01-13 00:00:00',
                                            u'number': u'84',
                                            u'start_date': u'2011-01-10 00:00:00'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'ID': {u'abbreviation': u'id',
        u'feature_flags': [],
        u'id': u'id',
        u'latest_csv_date': u'2012-05-01 09:09:38',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-id-csv.zip',
        u'latest_json_date': u'2012-05-01 23:10:26',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-id-json.zip',
        u'latest_update': u'2012-05-27 00:12:31',
        u'legislature_name': u'Idaho State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Idaho',
        u'session_details': {u'2011': {u'display_name': u'61st Legislature, 1st Regular Session',
                                       u'end_date': u'2011-04-07 00:00:00',
                                       u'start_date': u'2011-01-10 00:00:00',
                                       u'type': u'primary'},
                             u'2012': {u'display_name': u'61st Legislature, 2nd Regular Session',
                                       u'type': u'primary'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'IL': {u'abbreviation': u'il',
        u'feature_flags': [u'events'],
        u'id': u'il',
        u'latest_csv_date': u'2012-05-01 09:10:38',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-il-csv.zip',
        u'latest_json_date': u'2012-05-01 23:53:43',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-il-json.zip',
        u'latest_update': u'2012-05-27 08:23:15',
        u'legislature_name': u'The Illinois General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Illinois',
        u'session_details': {u'93rd': {u'display_name': u'93rd Regular Session',
                                       u'params': {u'GA': u'93',
                                                   u'SessionId': u'3'},
                                       u'president': u'Jones, E.',
                                       u'speaker': u'Madigan'},
                             u'94th': {u'display_name': u'94th Regular Session',
                                       u'params': {u'GA': u'94',
                                                   u'SessionId': u'50'},
                                       u'president': u'Jones, E.',
                                       u'speaker': u'Madigan'},
                             u'95th': {u'display_name': u'95th Regular Session',
                                       u'params': {u'GA': u'95',
                                                   u'SessionId': u'51'},
                                       u'president': u'Jones, E.',
                                       u'speaker': u'Madigan'},
                             u'96th': {u'display_name': u'96th Regular Session',
                                       u'params': {u'GA': u'96',
                                                   u'SessionId': u'76'},
                                       u'president': u'Cullerton',
                                       u'speaker': u'Madigan'},
                             u'97th': {u'display_name': u'97th Regular Session',
                                       u'params': {u'GA': u'97',
                                                   u'SessionId': u'84'},
                                       u'president': u'Cullerton',
                                       u'speaker': u'Madigan'},
                             u'Special_93rd': {u'display_name': u'93rd Special Session',
                                               u'params': {u'GA': u'93',
                                                           u'SessionID': u'14',
                                                           u'SpecSess': u'1'},
                                               u'president': u'Jones, E.',
                                               u'speaker': u'Madigan'},
                             u'Special_95th': {u'display_name': u'95th Special Session',
                                               u'params': {u'GA': u'95',
                                                           u'SessionId': u'52',
                                                           u'SpecSess': u'1'},
                                               u'president': u'Jones, E.',
                                               u'speaker': u'Madigan'},
                             u'Special_96th': {u'display_name': u'96th Special Session',
                                               u'params': {u'GA': u'96',
                                                           u'SessionId': u'82',
                                                           u'SpecSess': u'1'},
                                               u'president': u'Cullerton',
                                               u'speaker': u'Madigan'}},
        u'terms': [{u'end_year': 2004,
                    u'name': u'93rd',
                    u'sessions': [u'93rd', u'Special_93rd'],
                    u'start_year': 2003},
                   {u'end_year': 2006,
                    u'name': u'94th',
                    u'sessions': [u'94th'],
                    u'start_year': 2005},
                   {u'end_year': 2008,
                    u'name': u'95th',
                    u'sessions': [u'95th', u'Special_95th'],
                    u'start_year': 2007},
                   {u'end_year': 2010,
                    u'name': u'96th',
                    u'sessions': [u'96th', u'Special_96th'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'97th',
                    u'sessions': [u'97th'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'IN': {u'abbreviation': u'in',
        u'feature_flags': [u'subjects'],
        u'id': u'in',
        u'latest_csv_date': u'2012-05-01 09:08:08',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-in-csv.zip',
        u'latest_json_date': u'2012-05-01 22:08:16',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-in-json.zip',
        u'latest_update': u'2012-05-27 01:16:30',
        u'legislature_name': u'Indiana General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Indiana',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session',
                                       u'start_date': u'2011-01-05 00:00:00'},
                             u'2012': {u'display_name': u'2012 Regular Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'KS': {u'abbreviation': u'ks',
        u'feature_flags': [],
        u'id': u'ks',
        u'latest_csv_date': u'2012-05-01 09:12:29',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ks-csv.zip',
        u'latest_json_date': u'2012-05-02 00:28:36',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-ks-json.zip',
        u'latest_update': u'2012-05-04 02:26:02',
        u'legislature_name': u'Kansas State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Kansas',
        u'session_details': {u'2011-2012': {u'display_name': u'2011-2012 Regular Session',
                                            u'start_date': u'2011-01-12 00:00:00',
                                            u'type': u'primary'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'KY': {u'abbreviation': u'ky',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'ky',
        u'latest_csv_date': u'2012-05-01 09:00:59',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ky-csv.zip',
        u'latest_json_date': u'2012-05-01 15:28:33',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ky-json.zip',
        u'latest_update': u'2012-05-27 00:06:13',
        u'legislature_name': u'Kentucky General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Kentucky',
        u'session_details': {u'2011 Regular Session': {u'display_name': u'2011 Regular Session',
                                                       u'type': u'primary'},
                             u'2011SS': {u'display_name': u'2011 Extraordinary Session',
                                         u'type': u'special'},
                             u'2012RS': {u'display_name': u'2012 Regular Session',
                                         u'type': u'primary'},
                             u'2012SS': {u'display_name': u'2012 Extraordinary Session',
                                         u'type': u'special'}},
        u'terms': [{u'end_year': 2011,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011 Regular Session',
                                  u'2011SS',
                                  u'2012RS',
                                  u'2012SS'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'LA': {u'abbreviation': u'la',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'la',
        u'latest_csv_date': u'2012-05-01 09:11:51',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-la-csv.zip',
        u'latest_json_date': u'2012-05-02 15:03:34',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-la-json.zip',
        u'latest_update': u'2012-05-25 03:33:56',
        u'legislature_name': u'Louisiana Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 4,
        u'lower_chamber_title': u'Representative',
        u'name': u'Louisiana',
        u'session_details': {u'2009': {u'display_name': u'2009 Regular Session',
                                       u'end_date': u'2010-06-24 00:00:00',
                                       u'start_date': u'2010-04-27 00:00:00',
                                       u'type': u'primary'},
                             u'2010': {u'display_name': u'2010 Regular Session',
                                       u'end_date': u'2010-06-21 00:00:00',
                                       u'start_date': u'2010-03-29 00:00:00',
                                       u'type': u'primary'},
                             u'2011': {u'display_name': u'2011 Regular Session',
                                       u'type': u'primary'},
                             u'2011 1st Extraordinary Session': {u'display_name': u'2011, 1st Extraordinary Session',
                                                                 u'id': u'111es',
                                                                 u'type': u'special'},
                             u'2012': {u'display_name': u'2012 Regular Session',
                                       u'type': u'primary'}},
        u'terms': [{u'end_year': 2011,
                    u'name': u'2008-2011',
                    u'sessions': [u'2009',
                                  u'2010',
                                  u'2011 1st Extraordinary Session',
                                  u'2011'],
                    u'start_year': 2008},
                   {u'end_year': 2015,
                    u'name': u'2012-2015',
                    u'sessions': [u'2012'],
                    u'start_year': 2012}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'MA': {u'abbreviation': u'ma',
        u'feature_flags': [u'events'],
        u'id': u'ma',
        u'latest_csv_date': u'2012-05-01 09:08:49',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ma-csv.zip',
        u'latest_json_date': u'2012-05-01 22:45:50',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ma-json.zip',
        u'latest_update': u'2012-05-27 03:52:28',
        u'legislature_name': u'Massachusetts General Court',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Massachusetts',
        u'session_details': {u'186th': {u'display_name': u'186th Legislature',
                                        u'type': u'primary'},
                             u'187th': {u'display_name': u'187th Legislature',
                                        u'type': u'primary'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'186',
                    u'sessions': [u'186th'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'187',
                    u'sessions': [u'187th'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'MD': {u'abbreviation': u'md',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'md',
        u'latest_csv_date': u'2012-05-01 09:02:55',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-md-csv.zip',
        u'latest_json_date': u'2012-05-01 16:33:34',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-md-json.zip',
        u'latest_update': u'2012-05-27 01:28:25',
        u'legislature_name': u'Maryland General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Delegates',
        u'lower_chamber_term': 4,
        u'lower_chamber_title': u'Delegate',
        u'name': u'Maryland',
        u'session_details': {u'2007': {u'display_name': u'2007 Regular Session',
                                       u'end_date': u'2007-04-10 00:00:00',
                                       u'number': 423,
                                       u'start_date': u'2007-01-10 00:00:00',
                                       u'type': u'primary'},
                             u'2007s1': {u'display_name': u'2007, 1st Special Session',
                                         u'end_date': u'2007-11-19 00:00:00',
                                         u'number': 424,
                                         u'start_date': u'2007-10-29 00:00:00',
                                         u'type': u'special'},
                             u'2008': {u'display_name': u'2008 Regular Session',
                                       u'end_date': u'2008-04-07 00:00:00',
                                       u'number': 425,
                                       u'start_date': u'2008-01-09 00:00:00',
                                       u'type': u'primary'},
                             u'2009': {u'display_name': u'2009 Regular Session',
                                       u'end_date': u'2009-04-13 00:00:00',
                                       u'number': 426,
                                       u'start_date': u'2009-01-14 00:00:00',
                                       u'type': u'primary'},
                             u'2010': {u'display_name': u'2010 Regular Session',
                                       u'end_date': u'2010-04-12 00:00:00',
                                       u'number': 427,
                                       u'start_date': u'2010-01-13 00:00:00',
                                       u'type': u'primary'},
                             u'2011': {u'display_name': u'2011 Regular Session',
                                       u'end_date': u'2011-04-12 00:00:00',
                                       u'number': 428,
                                       u'start_date': u'2011-01-12 00:00:00',
                                       u'type': u'primary'},
                             u'2011s1': {u'display_name': u'2011, 1st Special Session',
                                         u'number': 429,
                                         u'type': u'special'},
                             u'2012': {u'display_name': u'2012 Regular Session',
                                       u'end_date': u'2012-04-09 00:00:00',
                                       u'number': 430,
                                       u'start_date': u'2012-01-11 00:00:00',
                                       u'type': u'primary'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2007-2010',
                    u'sessions': [u'2007',
                                  u'2007s1',
                                  u'2008',
                                  u'2009',
                                  u'2010'],
                    u'start_year': 2007},
                   {u'end_year': 2014,
                    u'name': u'2011-2014',
                    u'sessions': [u'2011', u'2011s1', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'ME': {u'abbreviation': u'me',
        u'feature_flags': [u'subjects'],
        u'id': u'me',
        u'latest_csv_date': u'2012-05-01 09:01:03',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-me-csv.zip',
        u'latest_json_date': u'2012-05-01 15:32:19',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-me-json.zip',
        u'latest_update': u'2012-05-27 03:04:27',
        u'legislature_name': u'Maine Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Maine',
        u'session_details': {u'124': {u'display_name': u'124th Legislature'},
                             u'125': {u'display_name': u'125th Legislature'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'124'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'125'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'MI': {u'abbreviation': u'mi',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'mi',
        u'latest_csv_date': u'2012-05-01 09:08:00',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-mi-csv.zip',
        u'latest_json_date': u'2012-05-01 22:03:22',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-mi-json.zip',
        u'latest_update': u'2012-05-27 01:47:15',
        u'legislature_name': u'Michigan Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Michigan',
        u'session_details': {u'2011-2012': {u'display_name': u'2011-2012 Regular Session',
                                            u'type': u'primary'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'MN': {u'abbreviation': u'mn',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'mn',
        u'latest_csv_date': u'2012-05-01 09:03:14',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-mn-csv.zip',
        u'latest_json_date': u'2012-05-01 16:56:55',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-mn-json.zip',
        u'latest_update': u'2012-05-27 04:08:01',
        u'legislature_name': u'Minnesota State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Minnesota',
        u'session_details': {u'2009-2010': {u'display_name': u'2009-2010 Regular Session',
                                            u'site_id': u'0862009',
                                            u'type': u'primary',
                                            u'votes_url': u'http://www.house.leg.state.mn.us/votes/getVotesls86.asp'},
                             u'2010 1st Special Session': {u'display_name': u'2010, 1st Special Session',
                                                           u'site_id': u'1862010',
                                                           u'type': u'special',
                                                           u'votes_url': u'http://www.house.leg.state.mn.us/votes/getVotesls8620101.asp'},
                             u'2010 2nd Special Session': {u'display_name': u'2010, 2nd Special Session',
                                                           u'site_id': u'2862010',
                                                           u'type': u'special'},
                             u'2011-2012': {u'display_name': u'2011-2012 Regular Session',
                                            u'site_id': u'0872011',
                                            u'type': u'primary',
                                            u'votes_url': u'http://www.house.leg.state.mn.us/votes/getVotesls87.asp'},
                             u'2011s1': {u'display_name': u'2011, 1st Special Session',
                                         u'site_id': u'1872011',
                                         u'type': u'special',
                                         u'votes_url': u'http://www.house.leg.state.mn.us/votes/getVotesls8720111.asp'}},
        u'terms': [{u'+biennium': u'86',
                    u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'2009-2010',
                                  u'2010 1st Special Session',
                                  u'2010 2nd Special Session'],
                    u'start_year': 2009},
                   {u'+biennium': u'87',
                    u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012', u'2011s1'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': u'http://en.wikipedia.org/wiki/Minnesota_Senate',
        u'upper_chamber_title': u'Senator'},
 'MO': {u'abbreviation': u'mo',
        u'feature_flags': [u'subjects'],
        u'id': u'mo',
        u'latest_csv_date': u'2012-05-01 09:09:01',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-mo-csv.zip',
        u'latest_json_date': u'2012-05-02 01:01:53',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-mo-json.zip',
        u'latest_update': u'2012-05-27 02:03:56',
        u'legislature_name': u'Missouri General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Missouri',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session',
                                       u'start_date': u'2011-01-26 00:00:00',
                                       u'type': u'primary'},
                             u'2012': {u'display_name': u'2012 Regular Session',
                                       u'start_date': u'2012-01-26 00:00:00',
                                       u'type': u'primary'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'MS': {u'abbreviation': u'ms',
        u'feature_flags': [u'subjects'],
        u'id': u'ms',
        u'latest_csv_date': u'2012-05-01 09:04:00',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ms-csv.zip',
        u'latest_json_date': u'2012-05-01 17:27:11',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ms-json.zip',
        u'latest_update': u'2012-05-27 00:04:54',
        u'legislature_name': u'Mississippi Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 4,
        u'lower_chamber_title': u'Representative',
        u'name': u'Mississippi',
        u'session_details': {u'2008': {u'display_name': u'2008 Regular Session'},
                             u'2009': {u'display_name': u'2009 Regular Session'},
                             u'20091E': {u'display_name': u'2009, 1st Extraordinary Session'},
                             u'20092E': {u'display_name': u'2009, 2nd Extraordinary Session'},
                             u'20093E': {u'display_name': u'2009, 3rd Extraordinary Session'},
                             u'2010': {u'display_name': u'2010 Regular Session'},
                             u'20101E': {u'display_name': u'2010, 1st Extraordinary Session'},
                             u'20102E': {u'display_name': u'2010, 2nd Extraordinary Session'},
                             u'2011': {u'display_name': u'2011 Regular Session'},
                             u'20111E': {u'display_name': u'2011, 1st Extraordinary Session'},
                             u'2012': {u'display_name': u'2012 Regular Session'}},
        u'terms': [{u'end_year': 2011,
                    u'name': u'2008-2011',
                    u'sessions': [u'2008',
                                  u'2009',
                                  u'20091E',
                                  u'20092E',
                                  u'20093E',
                                  u'20101E',
                                  u'20102E',
                                  u'2010',
                                  u'2011',
                                  u'20111E'],
                    u'start_year': 2008},
                   {u'end_year': 2015,
                    u'name': u'2012-2015',
                    u'sessions': [u'2012'],
                    u'start_year': 2012}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'MT': {u'abbreviation': u'mt',
        u'feature_flags': [],
        u'id': u'mt',
        u'latest_csv_date': u'2012-05-01 09:09:16',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-mt-csv.zip',
        u'latest_json_date': u'2012-05-02 00:58:21',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-mt-json.zip',
        u'latest_update': u'2012-05-27 02:09:46',
        u'legislature_name': u'Montana Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Montana',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session',
                                       u'years': [2011, 2012]}},
        u'terms': [{u'+session_number': u'62nd',
                    u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'NC': {u'abbreviation': u'nc',
        u'feature_flags': [u'subjects'],
        u'id': u'nc',
        u'latest_csv_date': u'2012-05-01 09:04:21',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-nc-csv.zip',
        u'latest_json_date': u'2012-05-01 17:36:42',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-nc-json.zip',
        u'latest_update': u'2012-05-27 00:54:27',
        u'legislature_name': u'North Carolina General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'North Carolina',
        u'session_details': {u'2009': {u'display_name': u'2009 Regular Session',
                                       u'start_date': u'2009-01-28 00:00:00',
                                       u'type': u'primary'},
                             u'2011': {u'display_name': u'2011 Regular Session',
                                       u'start_date': u'2011-01-26 00:00:00',
                                       u'type': u'primary'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'2009'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'ND': {u'abbreviation': u'nd',
        u'feature_flags': [],
        u'id': u'nd',
        u'latest_csv_date': u'2012-05-01 09:12:27',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-nd-csv.zip',
        u'latest_json_date': u'2012-05-02 00:25:42',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-nd-json.zip',
        u'latest_update': u'2012-05-27 00:52:49',
        u'legislature_name': u'North Dakota Legislative Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 4,
        u'lower_chamber_title': u'Representative',
        u'name': u'North Dakota',
        u'session_details': {u'62': {u'display_name': u'62nd Legislative Assembly',
                                     u'start_date': u'2011-01-04 00:00:00'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'62',
                    u'sessions': [u'62'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'NE': {u'abbreviation': u'ne',
        u'feature_flags': [],
        u'id': u'ne',
        u'latest_csv_date': u'2012-05-01 09:01:05',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ne-csv.zip',
        u'latest_json_date': u'2012-05-02 00:04:56',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-ne-json.zip',
        u'latest_update': u'2012-05-27 00:41:12',
        u'legislature_name': u'Nebraska Legislature',
        u'level': u'state',
        u'name': u'Nebraska',
        u'session_details': {u'102': {u'display_name': u'102nd Legislature',
                                      u'start_date': u'2011-01-05 00:00:00'},
                             u'102S1': {u'display_name': u'102nd Legislature, 1st Special Session',
                                        u'end_date': u'2011-11-22 00:00:00',
                                        u'start_date': u'2011-11-01 00:00:00'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'102', u'102S1'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'The Unicameral',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'NH': {u'abbreviation': u'nh',
        u'feature_flags': [],
        u'id': u'nh',
        u'latest_csv_date': u'2012-05-01 09:01:13',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-nh-csv.zip',
        u'latest_json_date': u'2012-05-01 15:36:30',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-nh-json.zip',
        u'latest_update': u'2012-05-27 00:10:16',
        u'legislature_name': u'New Hampshire General Court',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'New Hampshire',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session',
                                       u'zip_url': u'http://gencourt.state.nh.us/downloads/2011%20Session%20Bill%20Status%20Tables.zip'},
                             u'2012': {u'display_name': u'2012 Regular Session',
                                       u'zip_url': u'http://gencourt.state.nh.us/downloads/2012%20Session%20Bill%20Status%20Tables.zip'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'NJ': {u'abbreviation': u'nj',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'nj',
        u'latest_csv_date': u'2012-05-01 09:04:44',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-nj-csv.zip',
        u'latest_json_date': u'2012-05-01 18:12:52',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-nj-json.zip',
        u'latest_update': u'2012-05-27 00:13:55',
        u'legislature_name': u'New Jersey Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'General Assembly',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'New Jersey',
        u'session_details': {u'213': {u'display_name': u'2008-2009 Regular Session',
                                      u'start_date': u'2008-01-12 00:00:00'},
                             u'214': {u'display_name': u'2010-2011 Regular Session',
                                      u'start_date': u'2010-01-12 00:00:00'},
                             u'215': {u'display_name': u'2012-2013 Regular Session',
                                      u'start_date': u'2012-01-10 00:00:00'}},
        u'terms': [{u'end_year': 2009,
                    u'name': u'2008-2009',
                    u'sessions': [u'213'],
                    u'start_year': 2008},
                   {u'end_year': 2011,
                    u'name': u'2010-2011',
                    u'sessions': [u'214'],
                    u'start_year': 2010},
                   {u'end_year': 2013,
                    u'name': u'2012-2013',
                    u'sessions': [u'215'],
                    u'start_year': 2012}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': u'http://en.wikipedia.org/wiki/New_Jersey_Legislature#Elections_and_terms',
        u'upper_chamber_title': u'Senator'},
 'NM': {u'abbreviation': u'nm',
        u'feature_flags': [u'subjects'],
        u'id': u'nm',
        u'latest_csv_date': u'2012-05-01 09:11:55',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-nm-csv.zip',
        u'latest_json_date': u'2012-05-01 23:58:38',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-nm-json.zip',
        u'latest_update': u'2012-05-27 00:12:48',
        u'legislature_name': u'New Mexico Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'New Mexico',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session',
                                       u'slug': u'11%20Regular'},
                             u'2011S': {u'display_name': u'2011 Special Session',
                                        u'slug': u'11%20Special'},
                             u'2012': {u'display_name': u'2012 Regular Session',
                                       u'slug': u'12%20Regular'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2011S', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'NV': {u'abbreviation': u'nv',
        u'feature_flags': [u'subjects'],
        u'id': u'nv',
        u'latest_csv_date': u'2012-05-01 09:04:50',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-nv-csv.zip',
        u'latest_json_date': u'2012-05-01 18:16:55',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-nv-json.zip',
        u'latest_update': u'2012-05-27 00:47:40',
        u'legislature_name': u'Nevada Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'Assembly',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Nevada',
        u'session_details': {u'2010Special26': {u'display_name': u'26th Special Session (2010)',
                                                u'slug': u'26th2010Special',
                                                u'type': u'special'},
                             u'75': {u'display_name': u'2009 Regular Session',
                                     u'slug': u'75th2009',
                                     u'type': u'primary'},
                             u'76': {u'display_name': u'2011 Regular Session',
                                     u'slug': u'76th2011',
                                     u'type': u'primary'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'2010Special26', u'75'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'76'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'NY': {u'abbreviation': u'ny',
        u'feature_flags': [u'subjects'],
        u'id': u'ny',
        u'latest_csv_date': u'2012-05-01 09:05:09',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ny-csv.zip',
        u'latest_json_date': u'2012-05-01 18:59:22',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ny-json.zip',
        u'latest_update': u'2012-05-27 01:06:15',
        u'legislature_name': u'New York Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'Assembly',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Assembly Member',
        u'name': u'New York',
        u'session_details': {u'2011-2012': {u'display_name': u'2011 Regular Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'OH': {u'abbreviation': u'oh',
        u'feature_flags': [u'events'],
        u'id': u'oh',
        u'latest_csv_date': u'2012-05-01 09:05:11',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-oh-csv.zip',
        u'latest_json_date': u'2012-05-01 19:01:17',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-oh-json.zip',
        u'latest_update': u'2012-05-27 01:11:32',
        u'legislature_name': u'Ohio Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Ohio',
        u'session_details': {u'128': {u'display_name': u'128th Legislature'},
                             u'129': {u'display_name': u'129th Legislature',
                                      u'start_date': u'2011-01-03 00:00:00'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'128'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'129'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'OK': {u'abbreviation': u'ok',
        u'feature_flags': [u'subjects'],
        u'id': u'ok',
        u'latest_csv_date': u'2012-05-01 09:08:43',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ok-csv.zip',
        u'latest_json_date': u'2012-05-01 22:34:52',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ok-json.zip',
        u'latest_update': u'2012-05-27 00:46:26',
        u'legislature_name': u'Oklahoma Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Oklahoma',
        u'session_details': {u'2011-2012': {u'display_name': u'2011-2012 Regular Session',
                                            u'session_id': u'1200'},
                             u'2012SS1': {u'display_name': u'2012 Special Session',
                                          u'session_id': u'121X'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012', u'2012SS1'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'OR': {u'abbreviation': u'or',
        u'feature_flags': [],
        u'id': u'or',
        u'latest_csv_date': u'2012-05-01 09:01:19',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-or-csv.zip',
        u'latest_json_date': u'2012-05-01 15:42:18',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-or-json.zip',
        u'latest_update': u'2012-05-27 00:47:59',
        u'legislature_name': u'Oregon Legislative Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Oregon',
        u'session_details': {u'2011 Regular Session': {u'display_name': u'2011 Regular Session',
                                                       u'slug': u'11reg'},
                             u'2012 Regular Session': {u'display_name': u'2012 Regular Session',
                                                       u'slug': u'12reg'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011 Regular Session',
                                  u'2012 Regular Session'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'PA': {u'abbreviation': u'pa',
        u'feature_flags': [u'events', u'events'],
        u'id': u'pa',
        u'latest_csv_date': u'2012-05-01 09:05:40',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-pa-csv.zip',
        u'latest_json_date': u'2012-05-01 19:19:54',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-pa-json.zip',
        u'latest_update': u'2012-05-26 09:00:42',
        u'legislature_name': u'Pennsylvania General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Pennsylvania',
        u'session_details': {u'2009-2010': {u'display_name': u'2009-2010 Regular Session',
                                            u'type': u'primary'},
                             u'2009-2010 Special Session #1 (Transportation)': {u'display_name': u'2009-2010, 1st Special Session',
                                                                                u'type': u'special'},
                             u'2011-2012': {u'display_name': u'2011-2012 Regular Session',
                                            u'type': u'primary'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'2009-2010',
                                  u'2009-2010 Special Session #1 (Transportation)'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'PR': {u'abbreviation': u'pr',
        u'feature_flags': [],
        u'id': u'pr',
        u'latest_csv_date': u'2012-05-01 09:09:33',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-pr-csv.zip',
        u'latest_json_date': u'2012-05-01 23:08:07',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-pr-json.zip',
        u'latest_update': u'2012-05-27 04:39:14',
        u'legislature_name': u'Legislative Assembly of Puerto Rico',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 4,
        u'lower_chamber_title': u'Representative',
        u'name': u'Puerto Rico',
        u'session_details': {u'2009-2012': {u'display_name': u'2009-2012 Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2009-2012',
                    u'sessions': [u'2009-2012'],
                    u'start_year': 2009}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'RI': {u'abbreviation': u'ri',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'ri',
        u'latest_csv_date': u'2012-05-01 09:12:48',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ri-csv.zip',
        u'latest_json_date': u'2012-05-02 00:55:40',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-ri-json.zip',
        u'latest_update': u'2012-05-25 01:46:38',
        u'legislature_name': u'Rhode Island General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Rhode Island',
        u'session_details': {u'2012': {u'display_name': u'2012 Regular Session',
                                       u'start_date': u'2012-01-04 00:00:00',
                                       u'type': u'primary'}},
        u'terms': [{u'+start_date': u'2012-01-04 00:00:00',
                    u'end_year': 2012,
                    u'name': u'2012',
                    u'sessions': [u'2012'],
                    u'start_year': 2012}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'SC': {u'abbreviation': u'sc',
        u'feature_flags': [],
        u'id': u'sc',
        u'latest_csv_date': u'2012-05-01 09:12:25',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-sc-csv.zip',
        u'latest_json_date': u'2012-05-02 00:23:48',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-sc-json.zip',
        u'latest_update': u'2012-05-27 04:21:13',
        u'legislature_name': u'South Carolina Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'South Carolina',
        u'session_details': {u'119': {u'display_name': u'2011-2012 Regular Session',
                                      u'start_date': u'2010-11-17 00:00:00',
                                      u'type': u'primary'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'119',
                    u'sessions': [u'119'],
                    u'start_year': 2010}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'SD': {u'abbreviation': u'sd',
        u'feature_flags': [u'subjects'],
        u'id': u'sd',
        u'latest_csv_date': u'2012-05-01 09:05:47',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-sd-csv.zip',
        u'latest_json_date': u'2012-05-01 19:23:06',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-sd-json.zip',
        u'latest_update': u'2012-05-27 05:59:11',
        u'legislature_name': u'South Dakota State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'South Dakota',
        u'session_details': {u'2009': {u'display_name': u'2009 Regular Session'},
                             u'2010': {u'display_name': u'2010 Regular Session'},
                             u'2011': {u'display_name': u'2011 Regular Session',
                                       u'start_date': u'2011-01-11 00:00:00'},
                             u'2011s': {u'display_name': u'2011 Special Session'},
                             u'2012': {u'display_name': u'2012 Regular Session'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'2009', u'2010'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2011s', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'TN': {u'abbreviation': u'tn',
        u'feature_flags': [u'events'],
        u'id': u'tn',
        u'latest_csv_date': u'2012-05-01 09:13:13',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-tn-csv.zip',
        u'latest_json_date': u'2012-05-02 00:51:57',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-tn-json.zip',
        u'latest_update': u'2012-05-27 06:45:11',
        u'legislature_name': u'Tennessee General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Represenative',
        u'name': u'Tennessee',
        u'session_details': {u'106': {u'display_name': u'106th Regular Session',
                                      u'type': u'primary'},
                             u'107': {u'display_name': u'107th Regular Session',
                                      u'end_date': u'2012-01-10 00:00:00',
                                      u'start_date': u'2011-01-11 00:00:00',
                                      u'type': u'primary'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'106',
                    u'sessions': [u'106'],
                    u'start_year': 2009},
                   {u'end_year': 2011,
                    u'name': u'107',
                    u'sessions': [u'107'],
                    u'start_year': 2010}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'TX': {u'abbreviation': u'tx',
        u'capitol_maps': [{u'name': u'Capitol Complex',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.CapitolComplex.pdf'},
                          {u'name': u'Floor 1',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.Floor1.pdf'},
                          {u'name': u'Floor 2',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.Floor2.pdf'},
                          {u'name': u'Floor 3',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.Floor3.pdf'},
                          {u'name': u'Floor 4',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.Floor4.pdf'},
                          {u'name': u'Floor E1',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.FloorE1.pdf'},
                          {u'name': u'Floor E2',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.FloorE2.pdf'},
                          {u'name': u'Floor G',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.FloorG.pdf'},
                          {u'name': u'Monument Guide',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.MonumentGuide.pdf'},
                          {u'name': u'Sam Houston',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.SamHoustonLoc.pdf'},
                          {u'name': u'Wheelchair Access',
                           u'url': u'http://static.openstates.org/capmaps/tx/Map.WheelchairAccess.pdf'}],
        u'feature_flags': [u'events', u'subjects', u'capitol_maps'],
        u'id': u'tx',
        u'latest_csv_date': u'2012-05-01 09:06:28',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-tx-csv.zip',
        u'latest_json_date': u'2012-05-01 21:19:37',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-tx-json.zip',
        u'latest_update': u'2012-05-27 01:57:22',
        u'legislature_name': u'Texas Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Texas',
        u'session_details': {u'81': {u'display_name': u'81st Legislature',
                                     u'end_date': u'2009-06-01 00:00:00',
                                     u'start_date': u'2009-01-13 00:00:00',
                                     u'type': u'primary'},
                             u'811': {u'display_name': u'81st Legislature, 1st Called Session',
                                      u'end_date': u'2009-07-10 00:00:00',
                                      u'start_date': u'2009-07-01 00:00:00',
                                      u'type': u'special'},
                             u'82': {u'display_name': u'82nd Legislature',
                                     u'start_date': u'2011-01-11 00:00:00',
                                     u'type': u'primary'},
                             u'821': {u'display_name': u'82nd Legislature, 1st Called Session',
                                      u'type': u'special'}},
        u'terms': [{u'+type': u'primary',
                    u'end_year': 2010,
                    u'name': u'81',
                    u'sessions': [u'81', u'811'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'82',
                    u'sessions': [u'82', u'821'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'UT': {u'abbreviation': u'ut',
        u'feature_flags': [u'events', u'subjects'],
        u'id': u'ut',
        u'latest_csv_date': u'2012-05-01 09:06:36',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-ut-csv.zip',
        u'latest_json_date': u'2012-05-01 21:23:38',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-ut-json.zip',
        u'latest_update': u'2012-05-27 01:51:04',
        u'legislature_name': u'Utah State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Utah',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session',
                                       u'start_date': u'2011-01-24 00:00:00'},
                             u'2011S1': {u'display_name': u'2011, 1st Special Session'},
                             u'2011S2': {u'display_name': u'2011, 2nd Special Session'},
                             u'2011S3': {u'display_name': u'2011, 3rd Special Session'},
                             u'2012': {u'display_name': u'2012 General Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011',
                                  u'2011S1',
                                  u'2011S2',
                                  u'2011S3',
                                  u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'VA': {u'abbreviation': u'va',
        u'feature_flags': [u'subjects'],
        u'id': u'va',
        u'latest_csv_date': u'2012-05-01 09:07:23',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-va-csv.zip',
        u'latest_json_date': u'2012-05-01 21:44:10',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-va-json.zip',
        u'latest_update': u'2012-05-27 07:28:30',
        u'legislature_name': u'Virginia General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Delegates',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Delegate',
        u'name': u'Virginia',
        u'session_details': {u'2010': {u'display_name': u'2010 Regular Session',
                                       u'site_id': u'101',
                                       u'start_date': u'2010-01-13 00:00:00'},
                             u'2011': {u'site_id': u'111',
                                       u'start_date': u'2011-01-12 00:00:00'},
                             u'2011specialI': {u'site_id': u'112'},
                             u'2012': {u'site_id': u'121',
                                       u'start_date': u'2012-01-11 00:00:00'},
                             u'2012specialI': {u'site_id': u'122',
                                               u'start_date': u'2012-03-11 00:00:00'}},
        u'terms': [{u'end_year': 2011,
                    u'name': u'2009-2011',
                    u'sessions': [u'2010', u'2011', u'2011specialI'],
                    u'start_year': 2010},
                   {u'end_year': 2013,
                    u'name': u'2012-2013',
                    u'sessions': [u'2012', u'2012specialI'],
                    u'start_year': 2012}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'VT': {u'abbreviation': u'vt',
        u'feature_flags': [],
        u'id': u'vt',
        u'latest_csv_date': u'2012-05-01 09:06:41',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-vt-csv.zip',
        u'latest_json_date': u'2012-05-01 21:28:36',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-vt-json.zip',
        u'latest_update': u'2012-05-27 01:58:53',
        u'legislature_name': u'Vermont General Assembly',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Vermont',
        u'session_details': {u'2009-2010': {u'display_name': u'2009-2010 Regular Session',
                                            u'type': u'primary'},
                             u'2011-2012': {u'display_name': u'2011-2012 Regular Session',
                                            u'type': u'primary'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'2009-2010'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 2,
        u'upper_chamber_title': u'Senator'},
 'WA': {u'abbreviation': u'wa',
        u'feature_flags': [u'events', u'subjects'],
        u'id': u'wa',
        u'latest_csv_date': u'2012-05-01 09:07:37',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-wa-csv.zip',
        u'latest_json_date': u'2012-05-01 21:50:51',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-wa-json.zip',
        u'latest_update': u'2012-05-27 06:17:02',
        u'legislature_name': u'Washington State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Washington',
        u'session_details': {u'2009-2010': {u'display_name': u'2009-2010 Regular Session'},
                             u'2011-2012': {u'display_name': u'2011-2012 Regular Session'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'2009-2010'],
                    u'start_year': 2009},
                   {u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011-2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'WI': {u'abbreviation': u'wi',
        u'feature_flags': [u'subjects', u'events'],
        u'id': u'wi',
        u'latest_csv_date': u'2012-05-01 09:07:51',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-wi-csv.zip',
        u'latest_json_date': u'2012-05-01 21:57:33',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-wi-json.zip',
        u'latest_update': u'2012-05-26 14:49:03',
        u'legislature_name': u'Wisconsin State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'Assembly',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Wisconsin',
        u'session_details': {u'2009 Regular Session': {u'display_name': u'2009 Regular Session',
                                                       u'end_date': u'2011-01-03 00:00:00',
                                                       u'start_date': u'2009-01-13 00:00:00',
                                                       u'type': u'primary'},
                             u'2011 Regular Session': {u'display_name': u'2011 Regular Session',
                                                       u'end_date': u'2013-01-07 00:00:00',
                                                       u'start_date': u'2011-01-11 00:00:00',
                                                       u'type': u'primary'},
                             u'December 2009 Special Session': {u'display_name': u'Dec 2009 Special Session',
                                                                u'site_id': u'de9',
                                                                u'type': u'special'},
                             u'January 2011 Special Session': {u'display_name': u'Jan 2011 Special Session',
                                                               u'site_id': u'jr1',
                                                               u'type': u'special'},
                             u'June 2009 Special Session': {u'display_name': u'Jun 2009 Special Session',
                                                            u'site_id': u'jn9',
                                                            u'type': u'special'},
                             u'September 2011 Special Session': {u'display_name': u'Sep 2011 Special Session',
                                                                 u'site_id': u'se1',
                                                                 u'type': u'special'}},
        u'terms': [{u'end_year': 2010,
                    u'name': u'2009-2010',
                    u'sessions': [u'June 2009 Special Session',
                                  u'December 2009 Special Session',
                                  u'2009 Regular Session'],
                    u'start_year': 2009},
                   {u'end_year': 2011,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011 Regular Session',
                                  u'January 2011 Special Session',
                                  u'September 2011 Special Session'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'WV': {u'abbreviation': u'wv',
        u'feature_flags': [u'subjects'],
        u'id': u'wv',
        u'latest_csv_date': u'2012-05-01 09:09:46',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-wv-csv.zip',
        u'latest_json_date': u'2012-05-01 22:54:15',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-01-wv-json.zip',
        u'latest_update': u'2012-05-27 02:58:41',
        u'legislature_name': u'West Virginia Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Delegates',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Delegate',
        u'name': u'West Virginia',
        u'session_details': {u'2011': {u'display_name': u'2011 Regular Session'},
                             u'2012': {u'display_name': u'2012 Regular Session'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'},
 'WY': {u'abbreviation': u'wy',
        u'feature_flags': [],
        u'id': u'wy',
        u'latest_csv_date': u'2012-05-01 09:12:10',
        u'latest_csv_url': u'http://static.openstates.org/downloads/2012-05-01-wy-csv.zip',
        u'latest_json_date': u'2012-05-02 00:16:57',
        u'latest_json_url': u'http://static.openstates.org/downloads/2012-05-02-wy-json.zip',
        u'latest_update': u'2012-05-27 01:56:22',
        u'legislature_name': u'Wyoming State Legislature',
        u'level': u'state',
        u'lower_chamber_name': u'House of Representatives',
        u'lower_chamber_term': 2,
        u'lower_chamber_title': u'Representative',
        u'name': u'Wyoming',
        u'session_details': {u'2011': {u'display_name': u'2011 General Session',
                                       u'type': u'primary'},
                             u'2012': {u'display_name': u'2012 Budget Session',
                                       u'type': u'special'}},
        u'terms': [{u'end_year': 2012,
                    u'name': u'2011-2012',
                    u'sessions': [u'2011', u'2012'],
                    u'start_year': 2011}],
        u'upper_chamber_name': u'Senate',
        u'upper_chamber_term': 4,
        u'upper_chamber_title': u'Senator'}}
