bill_gpo_status_codes = {
	"ah": "Amendment",
	"ah2": "Amendment",
	"as": "Amendment",
	"as2": "Amendment",
	"ash": "Additional Sponsors",
	"sas": "Additional Sponsors",
	"sc": "Sponsor Change",
	"ath": "Resolution Agreed to",
	"ats": "Resolution Agreed to",
	"cdh": "Committee Discharged",
	"cds": "Committee Discharged",
	"cph": "Considered and Passed by the House",
	"cps": "Considered and Passed by the Senate",
	"eah": "Passed the House (Engrossed) with an Amendment",
	"eas": "Passed the Senate (Engrossed) with an Amendment",
	"eh": "Passed the House (Engrossed)",
	"ehr": "Passed the House (Engrossed)/Reprint",
	"eh_s": "Passed the House (Engrossed)/Star Print",
	"enr": "Passed Congress/Enrolled Bill",
	"renr": "Passed Congress/Re-enrolled",
	"es": "Passed the Senate (Engrossed)",
	"esr": "Passed the Senate (Engrossed)/Reprint",
	"es_s": "Passed the Senate (Engrossed)/Star Print",
	"fah": "Failed Amendment",
	"fps": "Failed Passage",
	"hdh": "Held at Desk in the House",
	"hds": "Held at Desk in the Senate",
	"ih": "Introduced",
	"ihr": "Introduced/Reprint",
	"ih_s": "Introduced/Star Print",
	"is": "Introduced",
	"isr": "Introduced/Reprint",
	"is_s": "Introduced/Star Print",
	"iph": "Indefinitely Postponed in the House",
	"ips": "Indefinitely Postponed in the Senate",
	"lth": "Laid on Table in the House",
	"lts": "Laid on Table in the Senate",
	"oph": "Ordered to be Printed",
	"ops": "Ordered to be Printed",
	"pch": "Placed on Calendar in the House",
	"pcs": "Placed on Calendar in the Senate",
	"pp": "Public Print",
	"rah": "Referred to House Committee (w/ Amendments)",
	"ras": "Referred to Senate Committee (w/ Amendments)",
	"rch": "Reference Change",
	"rcs": "Reference Change",
	"rdh": "Received by the House",
	"rds": "Received by the Senate",
	"reah": "Passed the House (Re-Engrossed) with an Amendment",
	"re": "Reprint of an Amendment",
	"res": "Passed the Senate (Re-Engrossed) with an Amendment",
	"rfh": "Referred to House Committee",
	"rfhr": "Referred to House Committee/Reprint",
	"rfh_s": "Referred to House Committee/Star Print",
	"rfs": "Referred to Senate Committee",
	"rfsr": "Referred to Senate Committee/Reprint",
	"rfs_s": "Referred to Senate Committee/Star Print",
	"rh": "Reported by House Committee",
	"rhr": "Reported by House Committee/Reprint",
	"rh_s": "Reported by House Committee/Star Print",
	"rs": "Reported by Senate Committee",
	"rsr": "Reported by Senate Committee/Reprint",
	"rs_s": "Reported by Senate Committee/Star Print",
	"rih": "Referral Instructions in the House",
	"ris": "Referral Instructions in the Senate",
	"rth": "Referred to House Committee",
	"rts": "Referred to Senate Committee",
	"s_p": "Star Print of an Amendment",
	}
	
