# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0005_auto_20180811_1342'),
        ('person', '0002_auto_20180811_1342'),
        ('committee', '0002_auto_20180811_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='OversightRelevantBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="One-sentence explaining how the bill relates to the topic. The sentence must be able to stand on its own because it will appear on both the oversight topic page and the bill's page.", max_length=256)),
                ('order', models.IntegerField(default=0, help_text='If different order numbers are given to relevant bills, they will be listed in ascending numeric order by this field.')),
                ('bill', models.ForeignKey(help_text='The related bill.', on_delete=django.db.models.deletion.CASCADE, related_name='oversight_topics', to='bill.Bill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OversightRelevantCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="One-sentence explaining how the committee relates to the topic. The sentence must be able to stand on its own because it will appear on both the oversight topic page and the committee's page.", max_length=256)),
                ('order', models.IntegerField(default=0, help_text='If different order numbers are given to relevant bills, they will be listed in ascending numeric order by this field.')),
                ('committee', models.ForeignKey(help_text='The related committee.', on_delete=django.db.models.deletion.CASCADE, related_name='oversight_topics', to='committee.Committee')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OversightRelevantPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text="One-sentence explaining how the person relates to the topic. The sentence must be able to stand on its own because it will appear on both the oversight topic page and the person's page.", max_length=256)),
                ('order', models.IntegerField(default=0, help_text='If different order numbers are given to relevant bills, they will be listed in ascending numeric order by this field.')),
                ('person', models.ForeignKey(help_text='The related person.', on_delete=django.db.models.deletion.CASCADE, related_name='oversight_topics', to='person.Person')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OversightTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title oversight topic for display purposes.', max_length=256)),
                ('slug', models.SlugField(help_text='The slug used in URLs for this topic.')),
                ('congress_start', models.IntegerField(default=115, help_text='The first Congress this oversight topic pertained to.')),
                ('congress_end', models.IntegerField(default=115, help_text='The last Congress this oversight topic pertained to, after which the topic is hidden from the main list.')),
                ('summary', models.CharField(help_text='One-sentence explaining what the topic is about.', max_length=256)),
                ('current_status', models.CharField(help_text='One-sentence explaining what the current status of this topic is.', max_length=256)),
                ('next_step', models.CharField(help_text='One-sentence explaining what the next procedural steps or expected actions for this topic are.', max_length=256)),
                ('narrative', models.TextField(blank=True, help_text='The long explanatory text for the topic in CommonMark format.')),
                ('post_date', models.DateTimeField(help_text="The date this oversight topic's summary was last updated.")),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date the oversight topic was created.')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text="The date the oversight topic's record was last saved.")),
                ('related_oversight_topics', models.ManyToManyField(blank=True, help_text='Other OversightTopics that are related.', related_name='_oversighttopic_related_oversight_topics_+', to='oversight.OversightTopic')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OversightUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title oversight topic for display purposes.', max_length=256)),
                ('summary', models.TextField(help_text='The summary text for the topic in CommonMark format.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date the oversight topic was created.')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text="The date the oversight topic's metadata/summary was last updated.")),
                ('topic', models.ForeignKey(help_text='The related topic.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='oversight.OversightTopic')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='oversightrelevantperson',
            name='topic',
            field=models.ForeignKey(help_text='The related topic.', on_delete=django.db.models.deletion.CASCADE, related_name='relevant_people', to='oversight.OversightTopic'),
        ),
        migrations.AddField(
            model_name='oversightrelevantcommittee',
            name='topic',
            field=models.ForeignKey(help_text='The related topic.', on_delete=django.db.models.deletion.CASCADE, related_name='relevant_committees', to='oversight.OversightTopic'),
        ),
        migrations.AddField(
            model_name='oversightrelevantbill',
            name='topic',
            field=models.ForeignKey(help_text='The related topic.', on_delete=django.db.models.deletion.CASCADE, related_name='relevant_bills', to='oversight.OversightTopic'),
        ),
        migrations.AlterUniqueTogether(
            name='oversightrelevantperson',
            unique_together=set([('topic', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='oversightrelevantcommittee',
            unique_together=set([('topic', 'committee')]),
        ),
        migrations.AlterUniqueTogether(
            name='oversightrelevantbill',
            unique_together=set([('topic', 'bill')]),
        ),
    ]
