# Generated by Django 2.0.8 on 2019-01-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversightrelevantbill',
            name='description',
            field=models.CharField(blank=True, help_text="One-sentence explaining how the bill relates to the topic. The sentence must be able to stand on its own because it will appear on both the oversight topic page and the bill's page.", max_length=500),
        ),
        migrations.AlterField(
            model_name='oversightrelevantcommittee',
            name='description',
            field=models.CharField(blank=True, help_text="One-sentence explaining how the committee relates to the topic. The sentence must be able to stand on its own because it will appear on both the oversight topic page and the committee's page.", max_length=500),
        ),
        migrations.AlterField(
            model_name='oversightrelevantperson',
            name='description',
            field=models.CharField(blank=True, help_text="One-sentence explaining how the person relates to the topic. The sentence must be able to stand on its own because it will appear on both the oversight topic page and the person's page.", max_length=500),
        ),
        migrations.AlterField(
            model_name='oversighttopic',
            name='current_status',
            field=models.CharField(help_text='One-sentence explaining what the current status of this topic is.', max_length=500),
        ),
        migrations.AlterField(
            model_name='oversighttopic',
            name='next_step',
            field=models.CharField(help_text='One-sentence explaining what the next procedural steps or expected actions for this topic are.', max_length=500),
        ),
        migrations.AlterField(
            model_name='oversighttopic',
            name='summary',
            field=models.CharField(help_text='One-sentence explaining what the topic is about.', max_length=500),
        ),
        migrations.AlterField(
            model_name='oversighttopic',
            name='title',
            field=models.CharField(help_text='The title of the oversight topic for display purposes.', max_length=256),
        ),
        migrations.AlterField(
            model_name='oversightupdate',
            name='title',
            field=models.CharField(help_text='The title oversight topic for display purposes.', max_length=500),
        ),
    ]
